---
title: "Dynamic Regression, ARIMAX and others"
output: html_notebook
---
```{r}
library(forecast)
library(fpp)

# Example 4.3. US consumption expenditure

fit.ex3 <- lm(consumption ~ income, data=usconsumption)
par(mfrow=c(1,2))
plot(usconsumption, ylab="% change in consumption and income",
     plot.type="single", col=1:2, xlab="Year")
legend("topright", legend=c("Consumption","Income"),
       lty=1, col=c(1,2), cex=.9)
plot(consumption ~ income, data=usconsumption, 
     ylab="% change in consumption", xlab="% change in income")
abline(fit.ex3)
summary(fit.ex3)

fcast <- forecast(fit.ex3, newdata = data.frame(income = c(-1, 1)))
par(mfrow = c(1, 1))
plot(fcast, ylab = "% change in consumption", xlab = "% change in income")
```

```{r}
# Example 4.4 Linear trend

fit.ex4 <- tslm(austa ~ trend)
f <- forecast(fit.ex4, h = 5, level = c(80, 95))
plot(f, ylab = "International tourist arrivals to Australia (millions)", 
     xlab = "t")
lines(fit.ex4$fitted, col = "blue")
summary(fit.ex4)

par(mfrow=c(2,2))
res3 <- ts(resid(fit.ex3), s = 1970.25, f = 4)
plot.ts(res3, ylab = "res (Consumption)")
abline(0, 0)
Acf(res3)
res4 <- resid(fit.ex4)
plot(res4, ylab = "res (Tourism)")
abline(0, 0)
Acf(res4)


```

```{r}
# Spurious regression

nf <- layout(matrix(c(1, 2, 3, 3), 2, 2, byrow = TRUE))
plot(ausair, ylab = "Air Passengers in Australia (millions)", xlab = "Year")
plot(guinearice, ylab = "Rice Production in Guinea (million tons) ", 
     xlab = "Year")
plot(c(guinearice), c(ausair), 
     xlab = "Rice Production in Guinea (million tons)", 
     ylab = "Air Passengers in Australia (millions)")

summary(lm(ausair ~ guinearice))
```


```{r}
#US expenditures
plot(usconsumption, xlab="Year",
     main="Quarterly changes in US consumption and personal income")

fit <- Arima(usconsumption[,1], xreg=usconsumption[,2],
             order=c(2,0,0))
tsdisplay(arima.errors(fit), main="ARIMA errors")

(fit2 <- Arima(usconsumption[,1], xreg=usconsumption[,2],
               order=c(1,0,2)))
Box.test(residuals(fit2),fitdf=5,lag=10,type="Ljung")

fcast <- forecast(fit2,xreg=rep(mean(usconsumption[,2]),8), h=8)
plot(fcast, main="Forecasts from regression with ARIMA(1,0,2) errors")

fit <- auto.arima(usconsumption[,1], xreg=usconsumption[,2])

```


```{r}
# Example 9.2. International visitors to Australia
plot(austa, xlab = "Year", ylab = "millions of people", 
     main = "Total annual international visitors to Australia")

(auto.arima(austa, d = 0, xreg = 1:length(austa)))

(auto.arima(austa, d = 1))

fit1 <- Arima(austa, order = c(0, 1, 0), include.drift = TRUE)
fit2 <- Arima(austa, order = c(2, 0, 0), include.drift = TRUE)

par(mfrow = c(2,1))
plot(forecast(fit2), 
     main = "Forecasts from linear trend + AR(2) error", ylim = c(1, 8))
plot(forecast(fit1), ylim = c(1, 8))

# Example 9.3 TV advertising and insurance quotations

plot(insurance, main="Insurance advertising and quotations", xlab="Year")

```


```{r}
# Lagged predictors. Test 0, 1, 2 or 3 lags.
Advert <- cbind(insurance[,2],
                c(NA,insurance[1:39,2]),
                c(NA,NA,insurance[1:38,2]),
                c(NA,NA,NA,insurance[1:37,2]))
colnames(Advert) <- paste("AdLag",0:3,sep="")

# Choose optimal lag length for advertising based on AIC 
# Restrict data so models use same fitting period
fit1 <- auto.arima(insurance[4:40,1], xreg=Advert[4:40,1], d=0)
fit2 <- auto.arima(insurance[4:40,1], xreg=Advert[4:40,1:2], d=0)
fit3 <- auto.arima(insurance[4:40,1], xreg=Advert[4:40,1:3], d=0)
fit4 <- auto.arima(insurance[4:40,1], xreg=Advert[4:40,1:4], d=0)

fit1
fit2
fit3
fit4

# Best model fitted to all data (based on AICc), which was the xreg=Advert[4:40,1:2], d=0
# Refit using all data
fit <- auto.arima(insurance[,1], xreg=Advert[,1:2], d=0)
fit

fc8 <- forecast(fit, xreg=cbind(c(Advert[40,1],rep(8,19)),rep(8,20)), h=20)

par(mfrow = c(1,1))
plot(fc8, main="Forecast quotes with advertising set to 8", ylab="Quotes")

```


```{r}
#neural nets
library(caret)
creditlog  <- data.frame(score=credit$score,
                         log.savings=log(credit$savings+1),
                         log.income=log(credit$income+1),
                         log.address=log(credit$time.address+1),
                         log.employed=log(credit$time.employed+1),
                         fte=credit$fte, single=credit$single)
fit  <- avNNet(score ~ log.savings + log.income + log.address +
                 log.employed, data=creditlog, repeats=25, size=3, decay=0.1,
               linout=TRUE)

fit <- nnetar(sunspotarea)
plot(forecast(fit,h=20))

fit <- nnetar(sunspotarea,lambda=0)
plot(forecast(fit,h=20))

```

